-- ============================================================================
-- Seed: users (from PEOPLE, RBAC role assigned via legacy assignMockRoles map),
-- audit_log seed history. Default login password for ALL seeded users:
--   Cattuong@2026
-- Username = legacy person id (e.g. "ct", "tgd", "cht", ...). CHANGE IN PROD.
-- ============================================================================

-- USERS (24)
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('ct','ct',NULL,'0MV+epK8vkTr9ljHAiTYY8Dumpq4hSDEGyvUTBbwraI=','w/1y0Y2tIfuw5Z/UMeSiww==','PBKDF2-SHA256-100000','Nguyễn Đăng Cường','Chủ tịch HĐQT','BCH','CT','grad-a','0913.***.001',NULL,'bch',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('tgd','tgd',NULL,'RMuSOp0mjtE8Q1ZiM9keH1KgRpC/G3OxLnao3kr92Sg=','dEY4U+cSqH32+EW5aHrbHA==','PBKDF2-SHA256-100000','Phan Văn Tú','Tổng Giám đốc','BCH','TGĐ','grad-e','0913.***.002',NULL,'bch',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('pt1','pt1',NULL,'7zlgAwLd23PJsVV033eUUH6ONrHnVbFmUFafLLHj+QM=','Thx0oFPACOdV0byr7RN6HA==','PBKDF2-SHA256-100000','Trần Quốc Bảo','Phó TGĐ – Trực chỉ huy','BCH','PT1','grad-c','0913.***.003',NULL,'bch',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('pt2','pt2',NULL,'PJoazInCriEV0o+mWHOvW2hnCgv0EhbTOfJuJbnhOVA=','GCkzGXVTnkIMtZLQBsPeQw==','PBKDF2-SHA256-100000','Lê Minh Hà','Phó TGĐ – Hậu cần & Đối ngoại','BCH','PT2','grad-d','0913.***.004',NULL,'relief',0);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('cht','cht',NULL,'uYzivEQF+Y4dEirQHToWINAovzkFJ4YLUAtah2wdqP8=','yWYW1xxxGyjuSdhX4/bxCA==','PBKDF2-SHA256-100000','Đỗ Xuân Thắng','Chỉ huy trưởng công trường','CT','CHT','grad-b','0968.***.101',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('chp1','chp1',NULL,'KxdKFjwrUK6RnlwGscaFaw9z77wplU8Fz9yCoL7NrIs=','yhFr1xre0UyEarPX3JDKeQ==','PBKDF2-SHA256-100000','Vũ Văn Đông','Chỉ huy phó – An toàn','CT','CHP1','grad-f','0968.***.102',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('chp2','chp2',NULL,'VwUvqH1Xm76tQ1BVtVmqzde6eMnEl9N/8bEj2dywsyM=','0J2thXhdeJnsHIQSkrfOTQ==','PBKDF2-SHA256-100000','Nguyễn Trọng Dũng','Chỉ huy phó – Kỹ thuật','CT','CHP2','grad-g','0968.***.103',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('atv','atv',NULL,'j7mXc/GGcdYrEh0pPsmlMBOWLpaSozQYlINdtocqriI=','uDkL5/E6Eno1kwf/UtykzA==','PBKDF2-SHA256-100000','Ngô Thị Hằng','ATVSV công trường','CT','ATV','grad-d','0968.***.104',NULL,'duty',0);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('tn1','tn1',NULL,'eFqcpF/siH4uAPXVYOEpQtDZfLPumwDNvYLGyilXu0c=','1PS52mfRnts62jrRTCZT2A==','PBKDF2-SHA256-100000','Phạm Ngọc Sơn','Trưởng BQL Nhà Thống Nhất','TN','TN1','grad-a','0912.***.201',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('tn2','tn2',NULL,'Cb7Eeipv6nvQuZXgi8g3iXKmCg/7j+rUmvTXAK+6v0Q=','tACQECs8umVn7NaHdbXvSA==','PBKDF2-SHA256-100000','Bùi Anh Tuấn','Kỹ thuật cụm TN','TN','TN2','grad-e','0912.***.202',NULL,'duty',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('eco1','eco1',NULL,'YQTN1WpmGYzcg4Eqh0uDL4rHYzgzFSPXSnGNlckMQqQ=','16JZOGIlt0KH6t2O09++iw==','PBKDF2-SHA256-100000','Hoàng Văn Nam','Trưởng BQL Cát Tường ECO','ECO','ECO1','grad-b','0912.***.301',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('eco2','eco2',NULL,'hKw1N5ak/SgWg8dVGfBnvVuHGt/pUdv3kU/7cGwlnYA=','4a5lU2Cj8QnLYix7tRlQ5Q==','PBKDF2-SHA256-100000','Lý Thu Trang','Trực toà A-ECO','ECO','ECO2','grad-d','0912.***.302',NULL,'duty',0);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('ctn1','ctn1',NULL,'jukpDUimHYDYTIpd/uLbuMCV+mySSmc6NrFAJG4ukhs=','kjxnu0iw83WwrHW3mMVdbw==','PBKDF2-SHA256-100000','Trần Đức Hải','Trưởng BQL Cát Tường New','CTN','CTN1','grad-c','0912.***.401',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('nm1','nm1',NULL,'H70O8ofyw7NTpex1v3mRstcPOY/4VLQnUPiUU+Pa604=','MXvjPTQgNwBNenDtXIaZDA==','PBKDF2-SHA256-100000','Đinh Công Thọ','Trưởng BQL Nhà M','NHAM','NM1','grad-g','0912.***.501',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('yp1','yp1',NULL,'ZhbPV75wQvzyCc3Ec+h4893C2+i3Tp+nUsuu6+sDMq8=','6wCfa6uWaV+ZJbVqwwsIdg==','PBKDF2-SHA256-100000','Nguyễn Văn Bình','Trưởng BQL CTS-YP','CTSYP','YP1','grad-e','0912.***.601',NULL,'unit_head',0);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('dy1','dy1',NULL,'/3W9FaNadVzAvFR21G6Nx3rSik6Qi8MeHMmjEL3fFco=','2MrIklqYQq0yQkJyXK8Ucw==','PBKDF2-SHA256-100000','Bs. Lê Thị Mai','Giám đốc TT Đông y – Khách sạn','TTDY','DY1','grad-d','0912.***.701',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('vp1','vp1',NULL,'gLs8JwqNsw/GUsV9JXvCjJCLbax1hD7JTPjJTtb0TRk=','0It/9PTTPMhKLgNIE0ANzg==','PBKDF2-SHA256-100000','Nguyễn Thị Lan','Trưởng HC-NS','VP','VP1','grad-a','0912.***.801',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('vp2','vp2',NULL,'aGt000Z+uMCzal3ePP0lz7BsJuXlQs3sHR41PJs8dW8=','1l/hFJ1pJysbwdv7z/bbJg==','PBKDF2-SHA256-100000','Trịnh Văn Khôi','Trưởng Mua hàng','VP','VP2','grad-b','0912.***.802',NULL,'warehouse',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('vp3','vp3',NULL,'os/utUCh1lW/qX8cIAb8owO8+j8kz6RvNyAJopIU3lw=','JfLm8QWDR7VFHfECKMSuJQ==','PBKDF2-SHA256-100000','Đặng Minh Hoà','Kế toán trưởng','VP','VP3','grad-c','0912.***.803',NULL,'audit',0);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('vp4','vp4',NULL,'bb4+ooxwsNk5TNAUn6DKYuGQ0wcjP/m9+HKlImq6JXg=','UmTGrpmTXze5NNsjE9sh8w==','PBKDF2-SHA256-100000','Phạm Văn Hậu','Hậu cần – Bếp','VP','VP4','grad-g','0912.***.804',NULL,'duty',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('mkt1','mkt1',NULL,'97Ixq7/befWRiPvin2mwVtMWWY+U4p+HLztXZ1pBPyk=','GOBRMqRU4WpEPk8NZ8xt7g==','PBKDF2-SHA256-100000','Vũ Hoàng Yến','Trưởng phòng Marketing','MKT','MKT1','grad-d','0912.***.901',NULL,'unit_head',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('vpct1','vpct1',NULL,'MhJuYqGI0B3nI/ctC+f6FtQQFWG8u14kjFsIOQtgVVc=','9/Hd8ameJj8c6HngrYyrtA==','PBKDF2-SHA256-100000','Đỗ Thị Hương','Chánh Văn phòng Chủ tịch','VPCT','VPC1','grad-a','0912.***.011',NULL,'super',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('it1','it1',NULL,'CVQNE5zSPpX4wPtflsvbM9JAnK3ki+vI45xhxqsBTos=','BLyXUp5S/mijx/Z8a3rHuw==','PBKDF2-SHA256-100000','Nguyễn Thanh Tùng','Trưởng IT / CĐS','IT','IT1','grad-e','0912.***.021',NULL,'super',1);
INSERT INTO users (id,username,email,password_hash,password_salt,password_algo,name,business_title,unit_code,short_label,gradient_class,phone,avatar_url,role_id,online) VALUES ('pc1','pc1',NULL,'T16aEXChxoDJ/hPETOo9AZjIvIMuZn+ccnVfcNLnpb4=','Holh7J+JWuTmi5jIxp9WYQ==','PBKDF2-SHA256-100000','Ls. Trần Văn Đạt','Trưởng Pháp chế','PC','PC1','grad-c','0912.***.031',NULL,'audit',0);

-- AUDIT_LOG seed history (8)
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('ad0c8983-e20a-4eec-b2aa-7006b1c29046','ct','approve','Dự án CTR-2026-01',NULL,NULL,'Phê duyệt ngân sách 850tr',NULL,NULL,NULL,NULL,'2026-07-17 05:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('24a1829b-d532-40f3-b3f4-00c278aa37b2','tgd','create','Nhiệm vụ TSK-201',NULL,NULL,'Tạo nhiệm vụ giao vp2',NULL,NULL,NULL,NULL,'2026-07-17 04:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('816ca717-2552-419f-9404-0b61ab515b15','it1','update','Cấu hình hệ thống',NULL,NULL,'Sửa Weather API key',NULL,NULL,NULL,NULL,'2026-07-17 02:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('1b56124d-b82b-4515-a2aa-35bc0025f969','vpct1','assign','Người dùng dy1',NULL,NULL,'Gán vai trò "Y tế đoàn"',NULL,NULL,NULL,NULL,'2026-07-16 23:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('b62b5636-02f4-480c-b23d-07b597b33918','pt1','activate','Cấp độ ĐỎ',NULL,NULL,'Kích hoạt kịch bản B3 (test)',NULL,NULL,NULL,NULL,'2026-07-16 19:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('b5fd52c1-e31f-4c1e-a910-a3ddbde07293','ct','login','Hệ thống',NULL,NULL,'Đăng nhập từ IP 10.0.1.24 (Chrome/Mac)',NULL,NULL,NULL,NULL,'2026-07-16 07:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('c5fb6aad-8ded-4a1f-bb57-56c78c852844','vp3','export','Báo cáo tài chính',NULL,NULL,'Xuất Excel BC-Yagi-2024',NULL,NULL,NULL,NULL,'2026-07-16 01:29:36.381');
INSERT INTO audit_log (id,actor_id,action,object_label,object_type,object_id,detail,before_json,after_json,ip,user_agent,created_at) VALUES ('f3961e0c-71fa-413b-b14b-bd86b6885f66','ct','delete','Người dùng test01',NULL,NULL,'Xoá user test',NULL,NULL,NULL,NULL,'2026-07-15 07:29:36.381');
